---
title: "Assignment 3: parallel computing"
author: "Stijn Hanssen"
date: "Oktober 2018"
output: html_document
---

### Clear working space
First step is to make sure that the working space is empty.
```{r}
# clear all variables
rm(list=ls()) 
```

### Set path working directory
The directory path is set to the stored dataset.
```{r}
# set working directory
setwd("C:/Users/stijn/Desktop/Master systems biology/Systems biology year 2/scientific computing/parallelprocessing") 
```

### Load packages
Setting the size memory for the project and loading the required packages for specific functions. If the packaged aren't present they will be automatically be downloaded.
```{r}
# setting working memory for this job to 8gb
options(java.parameters = "-Xmx8g")
# install pacman
if (!require("pacman")) suppressPackageStartupMessages(install.packages("pacman"))
# p_load: instal and load the packages
# ittertools: for proper nextElem support
# rcdk: acces functioality of jave framework
# doParallel: provides parallel backend for the dopar function
pacman::p_load("parallel","rcdk","itertools","doParallel")
```